# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-bwa}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francesco Strozzi"]
  s.date = %q{2011-03-22}
  s.description = %q{Ruby binding for BWA mapping software, built using Ruby-FFI library}
  s.email = %q{francesco.strozzi@gmail.com}
  s.extensions = ["ext/mkrf_conf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-bwa.gemspec",
    "doc/Bio.html",
    "doc/Bio/BWA.html",
    "doc/Bio/BWA/Library.html",
    "doc/_index.html",
    "doc/class_list.html",
    "doc/css/common.css",
    "doc/css/full_list.css",
    "doc/css/style.css",
    "doc/file.LICENSE.html",
    "doc/file.README.html",
    "doc/file_list.html",
    "doc/frames.html",
    "doc/index.html",
    "doc/js/app.js",
    "doc/js/full_list.js",
    "doc/js/jquery.js",
    "doc/method_list.html",
    "doc/top-level-namespace.html",
    "ext/COPYING",
    "ext/ChangeLog",
    "ext/NEWS",
    "ext/README",
    "ext/bamlite.c",
    "ext/bamlite.h",
    "ext/bntseq.c",
    "ext/bntseq.h",
    "ext/bwa.1",
    "ext/bwape.c",
    "ext/bwase.c",
    "ext/bwase.h",
    "ext/bwaseqio.c",
    "ext/bwt.c",
    "ext/bwt.h",
    "ext/bwt_gen/Makefile",
    "ext/bwt_gen/QSufSort.c",
    "ext/bwt_gen/QSufSort.h",
    "ext/bwt_gen/bwt_gen.c",
    "ext/bwt_gen/bwt_gen.h",
    "ext/bwt_lite.c",
    "ext/bwt_lite.h",
    "ext/bwtaln.c",
    "ext/bwtaln.h",
    "ext/bwtgap.c",
    "ext/bwtgap.h",
    "ext/bwtindex.c",
    "ext/bwtio.c",
    "ext/bwtmisc.c",
    "ext/bwtsw2.h",
    "ext/bwtsw2_aux.c",
    "ext/bwtsw2_chain.c",
    "ext/bwtsw2_core.c",
    "ext/bwtsw2_main.c",
    "ext/cs2nt.c",
    "ext/is.c",
    "ext/khash.h",
    "ext/kseq.h",
    "ext/ksort.h",
    "ext/kstring.c",
    "ext/kstring.h",
    "ext/kvec.h",
    "ext/main.c",
    "ext/main.h",
    "ext/mkrf_conf.rb",
    "ext/qualfa2fq.pl",
    "ext/simple_dp.c",
    "ext/simpletest.c",
    "ext/solid2fastq.pl",
    "ext/stdaln.c",
    "ext/stdaln.h",
    "ext/utils.c",
    "ext/utils.h",
    "lib/bio-bwa.rb",
    "lib/bio/bwa.rb",
    "lib/bio/bwa/library.rb",
    "test/data/testdata.fa",
    "test/data/testdata.long.fa",
    "test/data/testdata.short.fa",
    "test/helper.rb",
    "test/test_bio-bwa_basic.rb",
    "test/test_bio-bwa_make_index.rb",
    "test/test_bio-bwa_run_aln.rb",
    "test/test_bio-bwa_sam_conversion.rb"
  ]
  s.homepage = %q{http://github.com/fstrozzi/bioruby-bwa}
  s.licenses = ["MIT/GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Ruby binding for BWA mapping software}
  s.test_files = [
    "test/helper.rb",
    "test/test_bio-bwa_basic.rb",
    "test/test_bio-bwa_make_index.rb",
    "test/test_bio-bwa_run_aln.rb",
    "test/test_bio-bwa_sam_conversion.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.1"])
      s.add_development_dependency(%q<ffi>, [">= 1.0.5"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.1"])
      s.add_dependency(%q<ffi>, [">= 1.0.5"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.1"])
    s.add_dependency(%q<ffi>, [">= 1.0.5"])
  end
end

