# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-bwa}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francesco Strozzi"]
  s.date = %q{2011-02-04}
  s.description = %q{Ruby binding for BWA mapping software, built using Ruby-FFI library}
  s.email = %q{francesco.strozzi@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bio-bwa.gemspec",
    "lib/bio-bwa.rb",
    "lib/bio/bwa.rb",
    "lib/bio/ext/libbwa.dylib",
    "lib/bio/ext/libbwa.so",
    "lib/bio/library.rb",
    "test/data/testdata.fa",
    "test/data/testdata.long.fa",
    "test/data/testdata.short.fa",
    "test/helper.rb",
    "test/test_bio-bwa_basic.rb",
    "test/test_bio-bwa_make_index.rb",
    "test/test_bio-bwa_run_aln.rb",
    "test/test_bio-bwa_sam_conversion.rb"
  ]
  s.homepage = %q{http://github.com/fstrozzi/bioruby-bwa}
  s.licenses = ["MIT/GPLv3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Ruby binding for BWA mapping software}
  s.test_files = [
    "test/helper.rb",
    "test/test_bio-bwa_basic.rb",
    "test/test_bio-bwa_make_index.rb",
    "test/test_bio-bwa_run_aln.rb",
    "test/test_bio-bwa_sam_conversion.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.1"])
      s.add_development_dependency(%q<ffi>, [">= 1.0.5"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.1"])
      s.add_dependency(%q<ffi>, [">= 1.0.5"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.1"])
    s.add_dependency(%q<ffi>, [">= 1.0.5"])
  end
end

